export const surprises = [
    {
        uid: "FF914D",
        title: "Skill Swap",
        description: "Ask me to teach you any skill, in return teach me any skill of your expertise.",
        expiry: "07/05/2024",
        quantity: 1,
    },
    {
        uid: "00BF63",
        title: "1-hour video call",
        description: "Ask me anything on the video call and I cannot say no.",
        expiry: "27/10/2023",
        quantity: 1,
    },
    {
        uid: "004AAD",
        title: "Kiss me in 24 hours",
        description: "I'll aim to kiss you within 24 hours! (Works only if both of us are in Pune)",
        expiry: "never",
        quantity: "infinite",
    },
    {
        uid: "5CE1E6",
        title: "Hug me in 24 hours",
        description: "I'll aim to hug you within 24 hours! (Works only if both of us are in Pune)",
        expiry: "never",
        quantity: "infinite",
    },
    {
        uid: "5E17EB",
        title: "Leave me alone",
        description: "I will not disturb you until you talk to me. (You can use this as my punishment)",
        expiry: "never",
        quantity: "infinite",
    },
    {
        uid: "FF66C4",
        title: "Take me to a trip",
        description: "I will plan a trip for you to your desired place. All expenses on me.",
        expiry: "never",
        quantity: "infinite",
    },
    {
        uid: "FF3131",
        title: "Infinite Pictures",
        description: "I cannot say no for clicking pictures. Any pose you want!",
        expiry: "never",
        quantity: "infinite",
    },
    {
        uid: "C1FF72",
        title: "Boink",
        description: "Your desires all fulfilled; anything till you are satisfied.",
        expiry: "never",
        quantity: "infinite",
    },
]